### ISSUE TITLE
Support for ed25519 keys

### ISSUE THREAD

**Issue by lukasmalkmus** [golang-jwt/jwt#104]
While this is off standard, there are some JWT libraries out there supporting it as well as a draft: https://datatracker.ietf.org/doc/html/draft-ietf-jose-cfrg-curves-06

I would draft a PR, if maintainers allow it.

Edit: Also found this bit: https://datatracker.ietf.org/doc/html/rfc8037#page-10

**Comment by oxisto** [comment]
We do have `ed25519` support via https://github.com/golang-jwt/jwt/blob/main/ed25519.go or do you mean something different?

**Comment by lukasmalkmus** [comment]
Apologies! I was under the assumption that this fork wasn't yet far ahead with features from the original repository. Just looking at the README or the file tree would have saved me from opening this issue!

Excuse my foolishness :)
