### ISSUE TITLE
Compliance with published RFC7519

### ISSUE THREAD

**Issue by oxisto** [golang-jwt/jwt#11]
When the library was initially started, [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519) did not exist - only its drafts. This has lead to some shortcomings over the years where the implementation, especially of the claims, diverged from the now published RFC.

For example, the draft at the time of the writing of the claims struct actually stated that `iat`, `exp` and so on must be an `IntDate`, which did not include the possibility of non-integer date representations. It got then later changed to a `NumericDate` format in draft version 26, which - as @dunglas correctly pointed out - included also float representations (also strings).

The aim would be to be as backwards compatible as possible, e.g. with the introduction of  a new struct as suggested by @mfridman, which I will name for the lack of a better name `jwt.RFC7159Claims` for now.

This also was the original problem behind the audience mixup in #6

Points to consider (and possibly replaced with a new struct or function):

- [ ] The fields `ExpiresAt`, `IssuedAt`, `NotBefore` in `jwt.StandardClaims` are int64 instead of a (to be defined) `NumericDate` type. Probably solvable with a new struct
- [ ] The functions `VerifyIssuedAt`, `VerifyNotBefore`, `VerifyIssuedAt` of `jwt.StandardClaims` only compare against an int64 instead of the `NumericDate`. Also probably solvable with a new struct
- [ ] The functions `VerifyIssuedAt`, `VerifyNotBefore`, `VerifyIssuedAt` of `jwt.MapClaims` only compare against an int64 instead of the `NumericDate`. Trickier. I do not want to touch `jwt.MapClaims` too much. Probably the introduction of a new set of functions can be made and the old ones set to deprecated.
- [ ] `Audience` of `jwt.StandardClaims` should be a `[]string` instead of `string`. Could also be part of the new struct

Anything else that comes to mind?

At some point, it would also probably a good idea to check, whether [RFC8725](https://datatracker.ietf.org/doc/html/rfc8725) is also properly reflected in the implementation.

_Originally posted by @oxisto in https://github.com/golang-jwt/jwt/pull/9#discussion_r641039944_

**Comment by qbiqing** [comment]
> `Audience` of `jwt.StandardClaims` should be a `[]string` instead of `string`. Could also be part of the new struct

This would be useful to me.

**Comment by oxisto** [comment]
> > `Audience` of `jwt.StandardClaims` should be a `[]string` instead of `string`. Could also be part of the new struct
> 
> This would be useful to me.

Yeah, I created a new type `ClaimStrings` which can be either serialized/deserialized as a `[]string` or `string`. The PR is ready (#15), just waiting for an approval by another maintainer before I can merge this in.
