### ISSUE TITLE
request.ParseFromRequest not included?

### ISSUE THREAD

**Issue by tburschka** [golang-jwt/jwt#116]
Hello,

I'd like to use `request.ParseFromRequest` but it's not included when i'm install jwt:

```
go get github.com/golang-jwt/jwt/v4
```

Any thoughts?

**Comment by twocs** [comment]
The example shows that it's imported via:
```golang
import (
	"bytes"
	"crypto/rsa"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v4"
	"github.com/golang-jwt/jwt/v4/request"
)
```

https://github.com/golang-jwt/jwt/blob/main/http_example_test.go

Does it need the extra import?
`go get github.com/golang-jwt/jwt/v4/request`

**Comment by oxisto** [comment]
Yes you need the extra import, it is in the same module though. You can get it via `go get github.com/golang-jwt/jwt/v4/request` or just use it as done in the example and use `go mod tidy`
