### ISSUE TITLE
Consistent inner errors for validation errors

### ISSUE THREAD

**Issue by oxisto** [golang-jwt/jwt#135]
With PR #125 we can finally unwrap the `Inner` error of an `ValidationError`, for example to check for its underlying error, such as expiration or mis-formed token, e.g. using `error.Is`

However, we are not consistent in setting our inner errors. For example, for an expired map claim we set it to:
https://github.com/golang-jwt/jwt/blob/c435f38291bfed5322cf0f4ed12d1f8668ceaeb3/map_claims.go#L129

However, for our `RegisteredClaims` and `StandardClaims` we are setting it to:
https://github.com/golang-jwt/jwt/blob/c435f38291bfed5322cf0f4ed12d1f8668ceaeb3/claims.go#L59

In other cases we are actually using constant error strings, such as:
https://github.com/golang-jwt/jwt/blob/823c0140362292ebb64ad468503b4ed8264a5e7b/errors.go#L9

I would propose to harmonize this, possibly introducing an `ErrExpiredClaim` as a constant error string in this example to allow something like

```golang
token, err := jwt.Parse(...)
if err != nil && errors.Is(err, ErrExpiredClaim) {
  fmt.Printf("Your token is expired")
}
```

We could also potentially override `Is(err)` on validation error to check for the error using our flags rather than the error string.

I know that there is already a PR #100 open, but it introduces a lot of other changes and seems to be stale.

**Comment by mfridman** [comment]
Great job, thanks for putting this together. A few questions, 

1. Can we introduce [Go 1.13-style errors](https://go.dev/blog/go1.13-errors) in a backwards compatible way?
2. Do we need a third-party library such as [go-multierror](github.com/hashicorp/go-multierror) or [uber-go/multierr](https://github.com/uber-go/multierr)?

My biggest worry, is breaking existing behaviour.

**Comment by oxisto** [comment]
> Great job, thanks for putting this together. A few questions,
> 
> 1. Can we introduce [Go 1.13-style errors](https://go.dev/blog/go1.13-errors) in a backwards compatible way?
> 2. Do we need a third-party library such as [go-multierror](github.com/hashicorp/go-multierror) or [uber-go/multierr](https://github.com/uber-go/multierr)?
> 
> My biggest worry, is breaking existing behaviour.

I think we can do it backwards compatible in the following way:

1. Introduce a new `ErrTokenExpired` which is equal to the existing `errors.New("Token is expired")` of map claims and replace it in the map claims. 
2. Override `Is` of `ValidationError` to check, for example if an error is `ErrTokenExpired` by comparing it against the flags
3. (Potentially breaking, see below). Replace the error strings in `RegisteredClaims` and `StandardClaims` with `ErrTokenExpired`.

One could even argue that we could change the error strings of `RegisteredClaims` and `StandardClaims` since it does not change the API, however if one used the existing strings to compare the error (which is *highly* unlikely), this would break existing behaviour for them, so 3.) is a judgment call and not necessarily needed in the first place.
