### ISSUE TITLE
NumericDate marshals to JSON with decimals for large dates

### ISSUE THREAD

**Issue by JohanLindvall** [golang-jwt/jwt#158]
The following code results in str being equal to "5243700879.000001"

```go
buf, _ := jwt.NewNumericDate(time.Unix(5243700879, 0)).MarshalJSON()
str := string(buf)
```

I expected the JSON representation to be without decimals.

**Comment by oxisto** [comment]
Interesting. This could also be the issue why I had very very very subtle differences in some of the time-related unit tests. This could be an issue because of internal conversion rounding in `time.Unix` itself.

When marshalling we are using `FormatFloat` with `f` and a precision of `-1`, which has the following meaning according to the documentation: "The special precision -1 uses the smallest number of digits necessary".

This basically means that somehow your time is internally converted to the float `5243700879.000001` :(

**Comment by oxisto** [comment]
A possible fix, although a bit hacky, could be to manually set (or calculate) the precision based on `jwt.TimePrecision`, e.g. set it to precision 0 for `time.Seconds`, 3 for `time.Milliseconds`, etc.

**Comment by oxisto** [comment]
> Interesting, reading the spec for `NumericDate` in a bit more detail I'd also expect the default precision to have precision 0.
> 
> ```
>    NumericDate
>       A JSON numeric value representing the number of seconds from
>       1970-01-01T00:00:00Z UTC until the specified UTC date/time,
>       ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
>       2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
>       which each day is accounted for by exactly 86400 seconds, other
>       than that non-integer values can be represented.  See RFC 3339
>       [RFC3339] for details regarding date/times in general and UTC in
>       particular.
> ```
> 
> @oxisto Do we still have those irregular time-based tests, or did we simply increase the precision and they went away?

I think they went away after setting the time precision to seconds for the `time` package (we are using `time.Truncate`) and setting the float precision when marshalling to the magic `-1` value. But as you said, it might make more sense to also have the float precision at 0, if time precision is seconds.

**Comment by mfridman** [comment]
Let's do that, I think it's confusing to get a floating precision when the default precision is second.

I can't think of a better way to do this, so what you described makes sense to me. I don't think this is a breaking change, and instead can be treated as a bug fix. I see you assigned it to yourself, if you want I can pick this up..

**Comment by oxisto** [comment]
> Let's do that, I think it's confusing to get a floating precision when the default precision is second.
> 
> I can't think of a better way to do this, so what you described makes sense to me. I don't think this is a breaking change, and instead can be treated as a bug fix. I see you assigned it to yourself, if you want I can pick this up..

Sure, go ahead. I will have a look at your PR then
