### ISSUE TITLE
r.FillBytes undefined (type *big.Int has no field or method FillBytes)

### ISSUE THREAD

**Issue by hongbinhsu** [golang-jwt/jwt#160]
# github.com/golang-jwt/jwt/v4 （v4.2.0）

`Error: /home/runner/go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.2.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)

Error: /home/runner/go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.2.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
`

**Comment by oxisto** [comment]
> # github.com/golang-jwt/jwt/v4 （v4.2.0）
> `Error: /home/runner/go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.2.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
> 
> Error: /home/runner/go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.2.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes) `

As specified in the `go.mod`, this library needs at least Go 1.15. Using an even newer Go version is recommended. See #50 for a lengthy discussion.
