### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by conor-nsurely** [golang-jwt/jwt#167]
I am trying to parse a JWT generated by Keycloak using a public key(keyfunc.JWKS) from the appropriate Keycloak realm.

The JWT is valid according to jwt.io. jwt.ParseUnverified() works fine too, so the problem doesn't seem to be the token.

It throws this error upon parsing with jwt.Parse() :
`panic: runtime error: slice bounds out of range [1:0]`

I am creating the key function using this library  "github.com/MicahParks/keyfunc",
 like so:
```
		refreshInterval := time.Hour
		options := keyfunc.Options{
			RefreshInterval: refreshInterval,
			RefreshErrorHandler: func(err error) {
				logging.Log.Printf("There was an error with the jwt.KeyFunc\nError: %s", err.Error())
			},
		}
		jwks, err := keyfunc.Get(url, options)
```
This creates without issue (but I can open the issue on that repo if you think the problem lies there.)

The error is thrown by `jwt.Parse()` in the code below.
```

	verified_token, err := jwt.Parse(token, jwks.Keyfunc)
	if err != nil {
		logging.Log.Fatalf("Failed to parse the JWT.\nError: %s", err.Error())
	}

	// Check if the token is valid.
	if !verified_token.Valid {
		logging.Log.Fatalf("The token is not valid.")
	}
```

**Comment by oxisto** [comment]
It seems that this is an issue with the keyfunc library. Probably, it fails to lookup the kid in the JWKS somehow.

**Comment by conor-nsurely** [comment]
Okay thanks for that,I will open an issue there instead.
