### ISSUE TITLE
Allow custom fields in JWT header

### ISSUE THREAD

**Issue by jeroenjacobs79** [golang-jwt/jwt#172]
It seems the values of the header are more or less hard-coded:

https://github.com/golang-jwt/jwt/blob/e01ed05a3131827abc8404a9d4f6d4ee4a100501/token.go#L48-L51

However, some software require a custom field in the header, and example of this is the RabbitMQ JWT token plugin: https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2

It requires a "kid" in the header which identifies the public key that needs to be used for validation, eg:

```
{
  "kid": "my-token-pubkey",
  "alg": "RS256"
}
```

Is this functionality planned for the near future?

**Comment by jeroenjacobs79** [comment]
It seems the `kid:` header is listed in the RFC as well:
https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4

**Comment by oxisto** [comment]
The header is just a simple map. You can just set custom values like this:

```golang
t := jwt.NewWithClaims(jwt.SigningMethodES256, jwt.RegisteredClaims{
		Subject:   mySubject,
		ExpiresAt: jwt.NewNumericDate(expiry),
	})
t.Header["kid"] = „some_id“
```

**Comment by jeroenjacobs79** [comment]
Ugh, I didn't realize that field was exposed. I feel like an Idiot :)

**Comment by oxisto** [comment]
> Ugh, I didn't realize that field was exposed. I feel like an Idiot :)

No worries :)
