### ISSUE TITLE
Major uptick in "expired" token errors after upgrade from v3 to v4

### ISSUE THREAD

**Issue by reneesubsplash** [golang-jwt/jwt#178]
We recently did a package upgrade in one our services from

https://pkg.go.dev/gopkg.in/dgrijalva/jwt-go.v3@v3.2.0
https://pkg.go.dev/github.com/golang-jwt/jwt/v4@v4.3.0

And with no other code changes, we began getting a "token expired" error in our logs anywhere from 1-5 errors per SECOND.  
We're scratching our heads as to why one simple package upgrade would all of the sudden produce so many token expired errors.

Does anyone have an idea?  When comparing the old validation logic to the new validation logic, notable differences were switching from int64 to time.Time, and a related check for nil instead of 0.  We do have in-house service-to-service tokens that have no expiration date.  Would those kinds of tokens be triggering expired errors in the new package?

**Comment by oxisto** [comment]
Hi! Thanks for your issue. Ok, that is very weird indeed and you might be on to something with the time.Time comparison. I will check whether we have enough test cases for tokens that do not expire. Which claim struct are you using? MapClaims, the "old" StandardClaims or the "new" RegisteredClaims?

**Comment by scottmdahl** [comment]
@oxisto We’re still using the old StandardClaims.

(FYI, I work with @reneesubsplash 😁)

**Comment by mfridman** [comment]
Thank you for reporting this issue, we'll try to get to the bottom of it. It'd be useful to see the most basic repro of the jwt code path and how you're checking for errors, otherwise, I assume it's something like: 

- `NewWithClaims` where claims is `jwt.StandardClaims` (no embedding in custom type)
- The `ExpiresAt` is either 0 or not set at all (zero value)
- `ParseWithClaims` is called without any `jwt.WithX` options
- Checking if `err != nil` or catching specific errors: `errors.Is(err, jwt.ErrTokenExpired)`


> Would those kinds of tokens be triggering expired errors in the new package?

No, they should not be. iirc the verify exp method for standard claims bypasses expiry checks in `Valid()` whenever the exp claim is zero value.

**Comment by oxisto** [comment]
I have done some additional checks and tests, and tokens without any `exp` field or having the exp field set to `0` are regarded as valid. 

Can you share the payload of the service-to-service token (i.e. the claim) - without sharing a token itself?

**Comment by muddjones** [comment]
I work with @reneesubsplash and @scottmdahl as well. :-) We figured this out! We were filtering the token expired error messages from being added to our logs, however, when we switched libraries the error message changed so it was being missed in our filter and started showing up in our logs. Thank you for your collaboration and help!

**Comment by oxisto** [comment]
> I work with @reneesubsplash and @scottmdahl as well. :-) We figured this out! We were filtering the token expired error messages from being added to our logs, however, when we switched libraries the error message changed so it was being missed in our filter and started showing up in our logs. Thank you for your collaboration and help!

Good to know! Closing this issue then :)

**Comment by mfridman** [comment]
Thanks for reporting the issue. We've tried our best to maintain backwards compatibility while modernizing the library for the latest and greatest Go versions.

Apologies if this caused issued.

**Comment by muddjones** [comment]
Thank you! No worries at all. We improved our approach on our side too so that hopefully the risk of experiencing this again is minimized.
