### ISSUE TITLE
Single audience in RegisteredClaims

### ISSUE THREAD

**Issue by mkikyotani** [golang-jwt/jwt#190]
# summary

Currently `RegisteredClaims` generates array of audiences but our upstream system (Salesforce) expected single audience and thus it returned `Invalid Request` to us.

# current behaviour

## Input

```go
jwt.RegisteredClaims{
   Audience: jwt.ClaimStrings{"some-audience"},
}
```

## expected

```json
{
  "aud": "some-audience"
}
```

## actual

```json
{
  "aud": [
    "some-audience"
  ]
}
```

# Request

Can we change `RegisteredClaims` behaviour to this?

1. if single audience is provided to `RegisteredClaims`, set string to `aud` field
2. if array of audiences are provided to `RegisteredClaims`, set array of string to `aud` field.

I'm happy to raise a PR if you like

**Comment by oxisto** [comment]
This is configurable using the global variable `jwt. MarshalSingleStringAsArray`. Be aware, that this might create problems in concurrent coroutines.

https://github.com/golang-jwt/jwt/blob/0972257eba279bb357882afc11db8218644ad565/types.go#L28

**Comment by mkikyotani** [comment]
thanks, it's resolved my issue. Closed the ticket.

**Comment by snosratiershad** [comment]
Dear @oxisto, I'm going to work on the non-breaking way to do that.

**Comment by oxisto** [comment]
> Dear @oxisto, I'm going to work on the non-breaking way to do that.

Go ahead! Sounds like a good idea. I think this should now be possible with the (currently empty) parser options in place.

**Comment by snosratiershad** [comment]
@oxisto, my main idea is to modify the `ClaimStrings` from a type of `[]strings` to something like it: 
`type ClaimStrings struct {
    Strings  []string
    MarshalSingleStringAsArray  bool
}`
and than, using `ClaimStrings.Strings` when there is a return to something, and using the `MarshalSingleStringAsArray` in `MarshalJSON`. then add a parser option like `WithMarshalSingleStringAsArray`.  I've two questions:
1. Is that way non-breaking enough? is there any critical breaking cases I can't see or anything?
2. Which config should be in the priority? if there is both global variable and parser option changed for example

**Comment by oxisto** [comment]
Hmm after another careful look, I am now not too convinced that this is really possible. Changing the underlying type of `ClaimStrings` from a `[]string` to a struct is definitely breaking, because I suspect people will use something like `= []string{"myaud1", "myaud2"}` to assign values to it and this will not be possible anymore.

There is also not really any canonical way to inject additional parameters or context into the `MarshalJSON` function; probably the reason why we introduced this global in the first place. 🤔

**Comment by snosratiershad** [comment]
Is it reasonable to create another version of these functionalities? for example something like `MarshalJSONv2" which works with a more thread-safe logic?

**Comment by oxisto** [comment]
> Is it reasonable to create another version of these functionalities? for example something like `MarshalJSONv2` which works with a more thread-safe logic?

You would have to argue that with the creators of the standard library :) There was an issue to introduce a `Context` parameter into these functions, which could have been used for that, but that was denied: https://github.com/golang/go/issues/50422
