### ISSUE TITLE
cannot use jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {…}) (value of type *jwt.Token) as type string in assignment

### ISSUE THREAD

**Issue by mrichman** [golang-jwt/jwt#192]
I am using the example code to verify a JWT, and I get an error on this line:

`token, err := jwt.Parse(token, func(token *jwt.Token) (interface{}, error) { ... }`

Error: `cannot use jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {…}) (value of type *jwt.Token) as type string in assignment`

I'm using Go 1.18.

**Comment by hcasellas** [comment]
I have the same problem. which was the solution?

**Comment by mfridman** [comment]
Unrelated, let's continue the discussion in #247. This was likely a variable assignment typo.
