### ISSUE TITLE
Add package installation guidelines to README.md

### ISSUE THREAD

**Issue by morelmiles** [golang-jwt/jwt#197]
Hey, 
I'd like to add the package's installation guidelines to the README file. 
This would make it easier for the users to install the package in their projects by simply copying and pasting the command to their terminals. 

Could this issue be assigned to me? 

Let me know what you think of the above.

**Comment by mfridman** [comment]
Hey there, do you mean something like `go get github.com/golang-jwt/jwt/v4@latest` or the command line tool?

https://github.com/golang-jwt/jwt/tree/main/cmd/jwt#jwt-command-line-tool

**Comment by morelmiles** [comment]
hey @mfridman, 
yes, that's what i mean. 

is it vague? would love to get your opinion.

**Comment by mfridman** [comment]
If it helps users, even those new to Go, then it seems reasonable. Typically there would be an "Install" or "Installation" section in the readme with a command such as:

```
go get github.com/golang-jwt/jwt/v4@latest
```

And maybe a reference to the Go tooling installation: https://go.dev/doc/install#testing

**Comment by morelmiles** [comment]
Great, will send a PR.
