### ISSUE TITLE
token base64 encode error

### ISSUE THREAD

**Issue by dahaigj** [golang-jwt/jwt#201]
I got an generated token，but it seems not right
token:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZXRjIjoi5Lit5paH5rWL6K-VIiwiaXNzIjoiQ1MtV1giLCJleHAiOjE2NTE2MzU5NzV9.VHudOsegwOnW3GkJwkXux5oL-pO9FBPfG2z70gzz1fY

the information in token should be:
{"id":3,"etc":"中文测试","iss":"CS-WX","exp":1651635975}

but in fact the token can't be decoded,  first character '-' in token should be '+' , I think there is an error when generated the token

**Comment by qqiao** [comment]
The token decodes fine for me

**Comment by mfridman** [comment]
How are you decoding it, would it be possible to provide a small Go program so we can reproduce?

I tried the token you linked above (without verification) and was able to retrieve this claims:

```
{
  "etc": "中文测试",
  "exp": 1651635975,
  "id": 3,
  "iss": "CS-WX"
}
```

Also decoding the individual segments produces:

```
part: 0
raw segment: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
decoded segment: {"alg":"HS256","typ":"JWT"}
===
part: 1
raw segment: eyJpZCI6MywiZXRjIjoi5Lit5paH5rWL6K-VIiwiaXNzIjoiQ1MtV1giLCJleHAiOjE2NTE2MzU5NzV9
decoded segment: {"id":3,"etc":"中文测试","iss":"CS-WX","exp":1651635975}
===
part: 2
raw segment: VHudOsegwOnW3GkJwkXux5oL-pO9FBPfG2z70gzz1fY
decoded segment: [omitted]
```

**Comment by dahaigj** [comment]
Thanks a  lot @mfridman @qqiao 

The token is right. When encode in base64 , letter "+" is replaced with "-"   and  "/" is replaced with "_"  for safty concerns.  "+" and  "_"  need to be repalced backfoward before decode.

**Comment by qqiao** [comment]
@dahaigj @mfridman I think I understood the issue. There are 2 common alphabets used for base64 encoding, one is the URL safe alphabet, the other isn't. Usually most libraries would handle both of them just fine though.
