### ISSUE TITLE
How to handle multiple claim types

### ISSUE THREAD

**Issue by FabianTe** [golang-jwt/jwt#203]
Hi,

I might have a a case which is kind of special but maybe there is anyone who has an idea.

I use this great package to issue two types of JWTs:

- One is for actual human users. These tokens use a `type UserClaims struct` which embeds the standard claims type. Claims are email, firstName, lastName and similar.
- The other one is for bots. These use `type BotClaims struct` which also embeds the standard claims type but does not require the claims used for human users. Instead they have some special claims like botId and botType.

I can't really figure out how to use `jwt.Parse` or `jwt.ParseWithClaims` to allow usage of both claim types.

The only idea I have is using `MapClaims` but then I'd lose the benefit of having explicit types for the two claim types.

Has anyone experience with this? Sincerely.

**Comment by oxisto** [comment]
Maybe my line of thinking is too easy but why not have one claim type that works for both and just have the values empty / nil which are not relevant to the use case? More or less a `UserBotClaims`? There is not really a "dynamic" way of changing claims based on certain fields unfortunately.

**Comment by FabianTe** [comment]
@oxisto Hm, I like the idea. I might add a `TokenType string` field, which could directly contain the type, allowing an explicit switch-case for differentiation.
