### ISSUE TITLE
Security disclosure information

### ISSUE THREAD

**Issue by Waterdrips** [golang-jwt/jwt#21]
We need to create a process for individuals to be able to disclose security vulnerabilities responsibly.

I suggest: 
- We create a "SECURITY.md" file with contact information of one/some people here who will be designated security contact.
- Add information to our README/Contributing guide as to how to disclose security issues (not open issues/PRs without contacting security etc) 
- Discuses/publish our security patch processes and any backporting we intecnd to do (set the library users expectations)

**Comment by Waterdrips** [comment]
There are also some things we can enable on the repository like dependabot and some stuff in the "security" tab

**Comment by mfridman** [comment]
> There are also some things we can enable on the repository like dependabot and some stuff in the "security" tab

I enabled the Dependabot. 

I'll look into the code scanning, probably using Snyk or the native GitHub feature (CodeQL Analysis). Unless there is a preference for another tool? 

<img width="949" alt="CleanShot 2021-07-28 at 14 33 41@2x" src="https://user-images.githubusercontent.com/6278244/127377208-38c7d56f-4eac-4741-9c4a-f18585764f89.png">

**Comment by mfridman** [comment]
Going to setup CodeQL Analysis by GitHub
