### ISSUE TITLE
invalid character 'È' looking for beginning of value

### ISSUE THREAD

**Issue by mamycan** [golang-jwt/jwt#216]
I'm getting this error, is it a bug, or I'm doing wrong smt?

{
  "code": 401,
  "message": "invalid character 'È' looking for beginning of value"
}

v4.2.0

go version go1.18.2 darwin/arm64

**Comment by mfridman** [comment]
This sounds like a malformed token? I'm afraid without a repro, or even a code sample of how you're parsing a token there isn't much to go by.

**Comment by mamycan** [comment]
I fix it after upgrading package, I have no idea why I get this error.

**Comment by caotongxue565** [comment]
how did you deal with

**Comment by jockerz** [comment]
I got the issue when my `config.SECRET` value is empty string.
Set the value to resolve the issue

Here is the snippet code of my middleware

```go
func JwtAuthMiddleware(config *core.Config) fiber.Handler {
	return func(c *fiber.Ctx) error {
		claims, err := decode(c)

		if err != nil {
			return jwtError(c, err)
		}
               // ...skip
```

the `decode` function
```go
	decode := func(c *fiber.Ctx) (*jwt.MapClaims, error) {
		authHeader := c.Get("Authorization")

		// Parse bearer token
		token, err := jwt.Parse(authHeader[7:], func(token *jwt.Token) (interface{}, error) {
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				alg := token.Header["alg"]
				return nil, fmt.Errorf("unexpected authorization signing method: %v", alg)
			}

			return []byte(config.SECRET), nil  // <---------------
		})

		if err != nil {
			return nil, err
		}
	// --- skip
```

**Comment by mfridman** [comment]
I think this has come up before, but I think it's the caller's responsibility to validate their secret.

if config.SECRET == "" {
  return nil, errors.New("secret cannot be empty string")
}

If we add this logic in the package itself, we then start to get into conversations like .. is a 1-character secret _really_ secure, etc.

Also, I think it's best practice to validate _much_ earlier in the call stack (closer to where config struct is defined)
