### ISSUE TITLE
Example requested:  RS256 and .well-known/openid-configuration/jwk

### ISSUE THREAD

**Issue by scohen-examity** [golang-jwt/jwt#218]
Just need to authenticate a JWT token, I have the URL to the .well-known... set, not sure how to use the library to get the public key and provide to the decode function

**Comment by mfridman** [comment]
I presume you're implementing an OIDC flow, in which case you might want to take a look at https://github.com/coreos/go-oidc

It handles fetching the public key(s) from the discovery endpoint and leverages https://github.com/square/go-jose

**Comment by MicahParks** [comment]
I believe hat URL pattern typically leads to a "JWK Set". In the `README.md` of this repository, you'll see that [`github.com/MicahParks/keyfunc`](https://github.com/MicahParks/keyfunc) is mentioned as an extension for JWKS (JWK Set).

Here's an example from [`keyfunc`](https://github.com/MicahParks/keyfunc):
https://github.com/MicahParks/keyfunc/blob/master/examples/recommended_options/main.go
