### ISSUE TITLE
Parse returns capitalized error while Error constant isn't capitalized

### ISSUE THREAD

**Issue by isaacfolmsbee** [golang-jwt/jwt#224]
jwt.Parse returns a capitalized error while the Error constants aren't capitalized. This breaks directly checking the err against the constants.
```go
token, err := jwt.Parse(cookie, func(token *jwt.Token) (interface{}, error) {
    return []byte(secret), nil
})
if err == jwt.ErrTokenExpired {
    // This block should run when the token is expired, it doesn't
}
fmt.Println(err.Error()) // "Token is expired"
fmt.Println(jwt.ErrTokenExpired.Error()) // "token is expired"
```

I will say I'm extremely new to Go so my apologies if I am missing something obvious here, or a convention.

**Comment by oxisto** [comment]
Can you try using errors.Is(err, jwt.ErrTokenExpired) to compare the errors?

**Comment by isaacfolmsbee** [comment]
> Can you try using errors.Is(err, jwt.ErrTokenExpired) to compare the errors?

Oh my, yeah I completely forgot about this. Yes, using errors.Is() correctly matches them. Thank you so much, I'll close this.
