### ISSUE TITLE
Hello, I have two questions for you.

### ISSUE THREAD

**Issue by gh-zhangpeng** [golang-jwt/jwt#227]
Hello, I have two questions for you.

1. Why do I Validate Claims first and Perform Validation later?
2. In line 70 of Parser. go, ValidationError.Errors is used XOR, but Inner is overridden directly. This causes the actual error causes in the Validate Claims to be lost. You could do this with Errors, but it's a little inconvenient. Why is it designed that way?

**Comment by oxisto** [comment]
Fixed by #234
