### ISSUE TITLE
ErrorWrapper seems not to work

### ISSUE THREAD

**Issue by qazwsxedckll** [golang-jwt/jwt#228]
![image](https://user-images.githubusercontent.com/20088957/184172159-823d64f9-55f5-4a45-801f-b5b33d1a8bbd.png)

![image](https://user-images.githubusercontent.com/20088957/184171885-4d0613fd-1c7a-4824-9eeb-4d3a00df0cd2.png)

w gets the error bug lost it after return.

I'm really new to go, maybe a *ErrorWrapper should be used instead?

**Comment by oxisto** [comment]
From the screenshots you are using the archived version of this library (https://github.com/dgrijalva/jwt-go) in the unpublished v4 version, you should be using the import `github.com/golang-jwt/jwt/v4`, which also has proper support for `errors.Is`.
