### ISSUE TITLE
RegisteredClaims audience field

### ISSUE THREAD

**Issue by sam-hoffman** [golang-jwt/jwt#242]
The `RegisteredClaims` audience field must be a `ClaimString`, which seems to just be an array of strings. However, I'd like to be able to pass a single string to this field (the [RFC documentation](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) says this field MAY be a single string). 

This was possible with `StandardClaims`, but  `StandardClaims` is now deprecated. Would it be possible to allow a single string in the audience field in `RegisteredClaims`?

**Comment by oxisto** [comment]
I assume what you want to achieve is that if you pass a single string to the `ClaimString` array that it gets serialised as a single string, correct? like `{ "aud": "myaud" }`.

You can achieve that with `jwt.MarshalSingleStringAsArray = true`.

**Comment by sam-hoffman** [comment]
I am trying to create a registered claim object like this:

```
type Claims struct {
	...
	jwt.RegisteredClaims
}


def CreateClaims(...) Claims{
    audience := "my audience"
    ...
    return Claims{ ...
    RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    issuer,
			Audience:  audience,
			ExpiresAt: jwt.NewNumericDate(expiresAt),
			NotBefore: jwt.NewNumericDate(notBefore),
		}
    }
}
```

Even if I add `jwt.MarshalSingleStringAsArray = true` in the function (or try it with `jwt.MarshalSingleStringAsArray = false`), I get an incompatible assign error

**Comment by oxisto** [comment]
> 

Sorry for the long delay. Yes you need to convert it to a `ClaimString` for example `ClaimString{"myaud"}`. Unfortunately there is no other way to have the field support both single and multiple audiences, the field must always be an array but it is possible to just assign a single element to it.

**Comment by mfridman** [comment]
This appears to be resolved.. Feel free to continue to comment and/or raise open another issue.
