### ISSUE TITLE
crypto/ecdsa: verification error

### ISSUE THREAD

**Issue by wangyanxi2019** [golang-jwt/jwt#243]
I was using jwt es256 to decrypt when, appeared ：crypto/ecdsa: verification error，I don't know what's wrong. Could you help me check it
mycode：
	signingKey, err := ioutil.ReadFile(filePath)
	publicKey, err = jwt.ParseECPublicKeyFromPEM(signingKey)
        
token, err := jwt.ParseWithClaims(item, &transaction, func(token *jwt.Token) (interface{}, error) {
			//crypto/ecdsa: verification error
			return MyPublicKey, nil
		})

token.Valid = false and err= crypto/ecdsa: verification error

**Comment by mfridman** [comment]
Do you think could provide a full repro? No need to share the keys, please create new ones .. see https://pkg.go.dev/crypto/ecdsa

I suspect the issue is the public key.

**Comment by wangyanxi2019** [comment]
Thank you for your reply. Your idea is right. I have solved it. The problem with public keys
