### ISSUE TITLE
help on compile go project

### ISSUE THREAD

**Issue by softwareteamsmarter** [golang-jwt/jwt#244]
can you help me below issue how can possible to resovle ? 

in go lanague project

go: github.com/*/authorization@v1.0.3 requires
        github.com/dgrijalva/jwt-go@v0.0.0-20180308151308-06ea1031745c: invalid pseudo-version: does not match version-control timestamp (expected 20180308231308)
[root@git subscription]# go mod tidy
go: github.com/*/authorization@v1.0.3 requires
        github.com/dgrijalva/jwt-go@v0.0.0-20180308151308-06ea1031745c: invalid pseudo-version: does not match version-control timestamp (expected 20180308231308)
go: github.com/*/authorization@v1.0.3 requires
        github.com/dgrijalva/jwt-go@v0.0.0-20180308151308-06ea1031745c: invalid pseudo-version: does not match version-control timestamp (expected 20180308231308)

**Comment by mfridman** [comment]
Hey there, you're importing the older (archived) version of this repository.

The module you want is `github.com/golang-jwt/jwt/v4`

**Comment by softwareteamsmarter** [comment]
any help solution for this ?

**Comment by mfridman** [comment]
If you provide a full repro of the problem I'd be happy to help. Afaics are 2 issues:

1. you go.mod file probably has an invalid (pseudo) version
2. it's referencing the older package that has been archived: https://github.com/dgrijalva/jwt-go

You'll want to fetch the latest version from this repository, which should be a drop-in replacement:

```
go get github.com/golang-jwt/jwt/v4
```

And then change your imports to "github.com/golang-jwt/jwt/v4"

**Comment by mfridman** [comment]
Closing stale issue. Happy to help, just need a bit more information to debug.
