### ISSUE TITLE
cannot use func(token *jwt.Token) (interface{}, error)

### ISSUE THREAD

**Issue by hcasellas** [golang-jwt/jwt#247]
hello: I have this code:

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/golang-jwt/jwt/v4"
)

func main() {
const tokenString = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.drt_po6bHhDOF_FJEHTrK-KD8OGjseJZpHwHIgsnoTM"

	var keyfunc jwt.Keyfunc = func(token *jwt.Token) (interface{}, error) {
		return []byte("mysecret"), nil
	}
}

and I got this error:

cannot use func(token *jwt.Token) (interface{}, error) {…} (value of type func(token 
*"github.com/golang-jwt/jwt/v4".Token) (interface{}, error)) as type "github.com/golang-jwt/jwt/v4".Keyfunc in variable declaration

anyone can help  me?

**Comment by mfridman** [comment]
The code you have appears to be correct, example:

```go
package main

import (
	"fmt"
	"log"

	"github.com/golang-jwt/jwt/v4"
)

func main() {
	const tokenString = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.drt_po6bHhDOF_FJEHTrK-KD8OGjseJZpHwHIgsnoTM"
	var keyfunc jwt.Keyfunc = func(token *jwt.Token) (interface{}, error) {
		return []byte("mysecret"), nil
	}
	token, err := jwt.ParseWithClaims(tokenString, jwt.MapClaims{}, keyfunc)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v\n", token.Claims)
	// jwt.MapClaims{"iat":1.516239022e+09, "name":"John Doe", "sub":"1234567890"}
}
```

and go.mod

```
module example

go 1.19

require github.com/golang-jwt/jwt/v4 v4.4.2
```

Tested with `go version go1.19.2 darwin/arm64`

**Comment by mfridman** [comment]
Closing. Please reopen if you encounter more issues, ideally with a fully reproducible example.
