### ISSUE TITLE
update MIGRATION_GUIDE and VERSION_HISTORY

### ISSUE THREAD

**Issue by Waterdrips** [golang-jwt/jwt#25]
https://github.com/golang-jwt/jwt/blob/master/MIGRATION_GUIDE.md 

Is currently talking about migrating from v2 ro v3, this doesnt make much sense in this reop's context.

We could update this doc to discuss how to migrate from `dgrijalva/jwt-go/` to `golang-jwt/jwt` as a drop-in replacment, and then we can add sections in the future for new versions published from here

**Comment by oxisto** [comment]
> https://github.com/golang-jwt/jwt/blob/master/MIGRATION_GUIDE.md
> 
> Is currently talking about migrating from v2 ro v3, this doesnt make much sense in this reop's context.

It might, depending on the outcome of #17.

> 
> We could update this doc to discuss how to migrate from `dgrijalva/jwt-go/` to `golang-jwt/jwt` as a drop-in replacment, and then we can add sections in the future for new versions published from here

Yes, good idea.

**Comment by Waterdrips** [comment]
> > https://github.com/golang-jwt/jwt/blob/master/MIGRATION_GUIDE.md
> > Is currently talking about migrating from v2 ro v3, this doesnt make much sense in this reop's context.
> 
> It might, depending on the outcome of #17.

I we dont publish a v2 and just keep with v3 then we can link people to the `dgrijalva/jwt-go` migration guide from v2 to v3? not sure, just seems like a 5yr old doc might not be that useful for the handful of projects id guess are still on v2

**Comment by oxisto** [comment]
> > > https://github.com/golang-jwt/jwt/blob/master/MIGRATION_GUIDE.md
> > > Is currently talking about migrating from v2 ro v3, this doesnt make much sense in this reop's context.
> > 
> > 
> > It might, depending on the outcome of #17.
> 
> I we dont publish a v2 and just keep with v3 then we can link people to the `dgrijalva/jwt-go` migration guide from v2 to v3? not sure, just seems like a 5yr old doc might not be that useful for the handful of projects id guess are still on v2

That sound's reasonable. So then we might restructure it in a way that briefly explains how to:
* migrating to the new import path `golang-jwt/jwt`, possibly with the `v3.2.1+incompatible` version
* and then link to the old plan for older releases
