### ISSUE TITLE
Expires not setted

### ISSUE THREAD

**Issue by Satont** [golang-jwt/jwt#252]
```go
type Claims struct {
  jwt.RegisteredClaims
  ID     string   `json:"id"`
  Scopes []string `json:"scopes"`
  Login  string   `json:"login"`
}
claims := Claims{
  ID:     user.ID,
  Scopes: resp.Data.Scopes,
  Login:  user.Login,
}
claims.ExpiresAt = jwt.NewNumericDate(now.Add(10 * time.Minute))
token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

tokenString, err := token.SignedString([]byte(secret))
if err != nil {
  return "", err
}

return tokenString, nil
```

But result token doesn't have `exp` field.
```json
{
  "id": "128644134",
  "scopes": [
    "channel:manage:broadcast",
    "moderation:read"
  ],
  "login": "s4tont"
}
```
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyODY0NDEzNCIsInNjb3BlcyI6WyJjaGFubmVsOm1hbmFnZTpicm9hZGNhc3QiLCJtb2RlcmF0aW9uOnJlYWQiXSwibG9naW4iOiJzNHRvbnQifQ.qL2F8BB3CWQzJ3ecJje4zDO7roPtfT2EDK5E9xXuyO8`

**Comment by oxisto** [comment]
> 

Are you using the latest version? I cannot really reproduce this. I adapted your example to include all necessary variables and it works fine:

```
        secret := []byte{1, 2, 3, 4}
	now := time.Now()

	type Claims struct {
		jwt.RegisteredClaims
		ID     string   `json:"id"`
		Scopes []string `json:"scopes"`
		Login  string   `json:"login"`
	}
	claims := Claims{
		ID: "128644134",
		Scopes: []string{
			"channel:manage:broadcast",
			"moderation:read",
		},
		Login: "s4tont",
	}
	claims.ExpiresAt = jwt.NewNumericDate(now.Add(10 * time.Minute))
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	tokenString, err := token.SignedString([]byte(secret))
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s", tokenString)
```

Output: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY4NTM5OTYsImlkIjoiMTI4NjQ0MTM0Iiwic2NvcGVzIjpbImNoYW5uZWw6bWFuYWdlOmJyb2FkY2FzdCIsIm1vZGVyYXRpb246cmVhZCJdLCJsb2dpbiI6InM0dG9udCJ9.E6aJdHpnWZyXdc-pCsDY3awd2EIlXHbPtZw5oDOiG_Q`

```
{
  "exp": 1666853996,
  "id": "128644134",
  "scopes": [
    "channel:manage:broadcast",
    "moderation:read"
  ],
  "login": "s4tont"
}
```

**Comment by Satont** [comment]
`github.com/golang-jwt/jwt/v4 v4.4.2`

**Comment by oxisto** [comment]
> `github.com/golang-jwt/jwt/v4 v4.4.2`
> 
> Full code: https://github.com/Satont/tsuwari/blob/rewrite%2Fapi%2Fgo/apps/api-go/internal/api/auth/service.go#L47-L95
> 
> I took token from application console (did `fmt.Println(accessToken)`), passed to jwt and it have no exp. ¯_(ツ)_/¯

Ah. I think I see the issue. You are creating a `Claims` struct here. https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L47

Then you are assigning it `accessToken` here and setting the expiry date on `accessToken`. https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L55-L56. This copies the contents from `claims` to `accessToken`.

But you then use the original `claims` variable (which does not have the expiry set) in the createToken call: https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L57

You should either set the expiry on `claims` or use `accessToken` in the `createToken` function.

**Comment by Satont** [comment]
> > `github.com/golang-jwt/jwt/v4 v4.4.2`
> > Full code: https://github.com/Satont/tsuwari/blob/rewrite%2Fapi%2Fgo/apps/api-go/internal/api/auth/service.go#L47-L95
> > I took token from application console (did `fmt.Println(accessToken)`), passed to jwt and it have no exp. ¯_(ツ)_/¯
> 
> Ah. I think I see the issue. You are creating a `Claims` struct here. https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L47
> 
> Then you are assigning it to `accessToken` here and setting the expiry date on `accessToken`. https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L55-L56. This copies the contents from `claims` to `accessToken`. (before setting the expiry).
> 
> But you then use the original `claims` variable (which does not have the expiry set) in the createToken call: https://github.com/Satont/tsuwari/blob/4aa624fa7670fb4e9a6e8690a688cf0b0b4922d3/apps/api-go/internal/api/auth/service.go#L57
> 
> You should either set the expiry on `claims` or use `accessToken` in the `createToken` function.

I'm completely totally blind and waste much my time (about a hour), now i waste yours.

It works not, i'm appreciate your help and observation!
