### ISSUE TITLE
New generated token is always expired

### ISSUE THREAD

**Issue by Keda87** [golang-jwt/jwt#256]
Hi, I just used this package and I used to use [dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) before.

But, when I create a request to handler that use JWT middleware based on [this](https://echo.labstack.com/middleware/jwt/#custom-configuration), I always got this error `invalid or expired jwt`

Here is how I signed my token
```go
func GenerateAccessToken(userID uuid.UUID, email, phone, secret string) string {

	accessTokenClaim := &JWTCustomClaim{
		UserID: userID,
		Email:  email,
		Phone:  phone,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().UTC().Add(time.Minute * 15)), // expires within 15 minutes.
			NotBefore: jwt.NewNumericDate(time.Now().UTC()),
			IssuedAt:  jwt.NewNumericDate(time.Now().UTC()),
			Audience:  jwt.ClaimStrings{tokenAccessAudience},
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS512, accessTokenClaim)
	jwtToken, err := token.SignedString([]byte(secret))
	if err != nil {
		panic(err)
	}

	return jwtToken
}
```

and here is my middleware config
```go
jwtMiddleware = middleware.JWTWithConfig(middleware.JWTConfig{
	Claims:     &helper.JWTCustomClaim{},
	SigningKey: []byte(srv.conf.AppJWTSecretKey),
})
v1.PATCH("/sign-up", userHandler.ConfirmSignUp, jwtMiddleware)
```

**Comment by Keda87** [comment]
My bad, I was supposed to use `jwt.SigningMethodHS256` instead of `jwt.SigningMethodHS512`

**Comment by mfridman** [comment]
Glad you figured it out @Keda87. Something to call out though, that example you linked uses an old non-module version of the project. You'll want to make sure you're using the latest major version, which is currently:

```
import "github.com/golang-jwt/jwt/v4"
```
