### ISSUE TITLE
PRISMA-2022-0270 security vulnerability in version v4.4.2

### ISSUE THREAD

**Issue by vishweshwarp** [golang-jwt/jwt#258]
Found the vulnerability with CVE code PRISMA-2022-0270 in version v4.4.2. Can we get this fixed?

Vulnerability description: 
`github.com/golang-jwt/jwt/v4 module from all versions is vulnerable to Denial of Service (DoS) due to token without ExpiresAt can cause panic.`

**Comment by oxisto** [comment]
> 

That is the problem with using some cloud security software from a vendor, which does not even bother reporting it to the original repo but just assigning a proprietary own number. It has no assigned CVE number. The actual CVE 2022-0270 is from a totally different product. Not sure what else we can do from our side on this.

**Comment by mfridman** [comment]
I suggest we close this issue. Not much more to do here and @oxisto answer's are spot on.
