### ISSUE TITLE
Add GitHub Pages documentation site

### ISSUE THREAD

**Issue by mfridman** [golang-jwt/jwt#273]
We've chatted about this in various PRs and Issues, so let's add a GitHub Pages documentation website.

Not an exhaustive list, but the goal is to...

- provide copy/paste examples, with explanations
- document gotchas and best practices
- add a frequently asked questions list
- ...

**Comment by mfridman** [comment]
This has been setup in https://github.com/golang-jwt/jwt-docs, on every merge to `main` that repository pushes to [gh-pages branch](https://github.com/golang-jwt/jwt/tree/gh-pages) within this repository.

It's currently live here: https://golang-jwt.github.io/jwt/

This was an experiment. We can continue to build out that documentation site, or we can continue adding .md files within this repository. Let me know your thoughts @oxisto

**Comment by oxisto** [comment]
> This has been setup in https://github.com/golang-jwt/jwt-docs, on every merge to `main` that repository pushes to [gh-pages branch](https://github.com/golang-jwt/jwt/tree/gh-pages) within this repository.
> 
> It's currently live here: https://golang-jwt.github.io/jwt/
> 
> This was an experiment. We can continue to build out that documentation site, or we can continue adding .md files within this repository. Let me know your thoughts @oxisto

My slight preference would be towards adding a `docs` repo here. In this case one could change code and documentation at the same time, e.g. in a PR.

**Comment by mfridman** [comment]
My only concern is docs typically bloat the project and non-code commits make the git history hard to grok. I suggest we start with a separate jwt-docs site, and once we have some content and it's not overly big .. we can consider moving it into this repository?

**Comment by oxisto** [comment]
> My only concern is docs typically bloat the project and non-code commits make the git history hard to grok. I suggest we start with a separate jwt-docs site, and once we have some content and it's not overly big .. we can consider moving it into this repository?

That's a good point. Probably, especially in the beginning we might have a lot of doc commits. Lets keep it separate then for now.

**Comment by mfridman** [comment]
We'll continue to flush out https://github.com/golang-jwt/jwt-docs and revisit whether it should be merged into this repository or kept as-is.
