### ISSUE TITLE
Be able to skip b64 encoding on payload

### ISSUE THREAD

**Issue by emilpriver** [golang-jwt/jwt#294]
Hey,
I did have a issue where I needed to prevent signing the jwt payload with b64. Is there a option to skip b64 encoding or is it possible to add it?

**Comment by emilpriver** [comment]
I am working on a PR for this

**Comment by oxisto** [comment]
I am not quite sure what you want to achieve? If you do not do any base64 encoding, the result will not be a valid token.

**Comment by emilpriver** [comment]
Hi @oxisto 

We do often when we work with banks need to create a detached JWS signature(a normal JWT without signed claims). I did add a PR, should we continue to discuss there? :D

**Comment by emilpriver** [comment]
Or is this something the lib already have support for? ☺️
