### ISSUE TITLE
"aud" claim type

### ISSUE THREAD

**Issue by Virviil** [golang-jwt/jwt#307]
https://pkg.go.dev/github.com/golang-jwt/jwt#StandardClaims "aud" type is string.
The problem is that https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.3 specifies that 

> In the general case, the "aud" value is an **array** of case-sensitive strings, each containing a StringOrURI value.

This attitude can't be emulated with standard claims, because type is specified as `string`.
One can encode json array into string, but it's unnecessary complication.
Another option - to use custom claims.

Any suggestions?

Appending example of JWT with array-typed audience:
https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJhdWQiOlsiaG9zdDEuY29tIiwiaG9zdDIuY29tIl19.o8PWKkFWMx_iYWC9JtdAgusgYPuQ61rtnPszkD857jg

**Comment by mfridman** [comment]
Going to close this issue. But if you need a bit more help let us know and/or reopen the issue.
