### ISSUE TITLE
Incorporate string array in `aud` field from the original v4 branch

### ISSUE THREAD

**Issue by dcormier** [golang-jwt/jwt#32]
The original repo has [a pretty complete v4 release](https://github.com/dgrijalva/jwt-go/tree/release_4_0_0) that I'm using ([docs](https://pkg.go.dev/github.com/dgrijalva/jwt-go/v4)).

As I recall, I needed v4 because of [this change](https://github.com/dgrijalva/jwt-go/blob/release_4_0_0/VERSION_HISTORY.md#user-content-400):

> Added new type, `ClaimStrings`, which will correctly handle properties such as `aud` that can be either an array of strings or a single string. `ClaimStrings` is an alias to `[]string`, but with custom decoding behavior. This means all the built in `aud` validation behavior now expects `[]string` instead of `string`. This was a common request.

It would be nice to see that picked up and moved forward, as well.

**Comment by oxisto** [comment]
I have tried to put that functionality in https://github.com/golang-jwt/jwt/pull/15. Could you have a look whether this fulfills your use case?

**Comment by dcormier** [comment]
It looks like that probably would handle that my use case.

**Comment by dunglas** [comment]
This is currently a BC break. When using `StandardClaims` with an `aud` field containing a string, this error is now thrown: `unable to parse JWT: json: cannot unmarshal array into Go struct field claims.aud of type string`.

Using the new `RegisteredClaims` introduced in https://github.com/golang-jwt/jwt/pull/15 works properly, but even with this patch the BC break is still present of the deprecated `StandardClaims` struct.
