### ISSUE TITLE
Request for ValidationError Support in Version 5

### ISSUE THREAD

**Issue by LieLieLiekey** [golang-jwt/jwt#321]
Hello golang-jwt maintainers,

I am currently using your open-source golang-jwt library and it has been a great help in my projects. However, I have noticed that the latest version, v5, does not support ValidationError. This has been inconvenient for the callers to identify the errors or handle error codes.

Considering the practical utility that this feature offers, I would like to propose the addition of ValidationError support to this version. I believe this would greatly improve the error handling capabilities of your library and would be beneficial to many developers.

I see that this has been discussed in a previous issue: https://github.com/golang-jwt/jwt/pull/125. I kindly urge you to reconsider the implementation of this feature for the betterment of this library.

Thank you for your time and for considering this request. I appreciate your efforts in maintaining this library.

Best regards

**Comment by oxisto** [comment]
You should be able to use `errors.Is` with the specific error that you want. This should work independently whether a joined error or the old validation error is used. See the following example:

https://github.com/golang-jwt/jwt/blob/33d62b4dae7d7398086e4afda2dcaeab2a71f3df/example_test.go#L158-L181

**Comment by LieLieLiekey** [comment]
oh, i got it, thanks very much!
