### ISSUE TITLE
KeyFunc should be able to return a slice

### ISSUE THREAD

**Issue by notrobpike** [golang-jwt/jwt#339]
In order to facilitate key rotation, without using a `kid` or other explicit claim, the keyfunc should be allowed to return a slice of eligible keys, and then the verifier will try each in turn until success or running out of keys.

It would be pretty simple to make it backwards compatible with the current usage of returning a single key.

**Comment by oxisto** [comment]
We are currently looking into this in https://github.com/golang-jwt/jwt/pull/328

**Comment by oxisto** [comment]
Fixed by #344
