### ISSUE TITLE
 Used for two different module paths error in go mod tidy

### ISSUE THREAD

**Issue by turkenh** [golang-jwt/jwt#37]
I am trying to follow the steps in [the migration guide ](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md#gomod-replacement) however, I am getting the following error with `go mod tidy`:

```
go mod tidy
go: finding module for package github.com/golang-jwt/jwt/test
go: finding module for package github.com/golang-jwt/jwt/request
go: finding module for package github.com/golang-jwt/jwt
go: found github.com/golang-jwt/jwt in github.com/golang-jwt/jwt v3.2.1+incompatible
go: found github.com/golang-jwt/jwt/request in github.com/golang-jwt/jwt v3.2.1+incompatible
go: found github.com/golang-jwt/jwt/test in github.com/golang-jwt/jwt v3.2.1+incompatible
go: github.com/golang-jwt/jwt@v3.2.1+incompatible used for two different module paths (github.com/dgrijalva/jwt-go and github.com/golang-jwt/jwt)
```

Here is the PR: https://github.com/upbound/universal-crossplane/pull/167

Any ideas how to fix that?

**Comment by oxisto** [comment]
I had a quick look into your PR and I fear that you are stuck in the middle for now. The `replace` route only works of you keep the original import path. Replacing the import path will not replace transitive imports.

My best guess would be to switch back to the old dgrijalva import path and use replace. Then once, your transitive dependency also switches to the new import path, remove the replace and switch the import path.

**Comment by jkawamoto** [comment]
Same here. I only run `go mod edit` and `go mod tidy` without editing any code but get this error:

```
$ go mod edit -replace github.com/dgrijalva/jwt-go=github.com/golang-jwt/jwt@v3.2.1+incompatible
$ go mod tidy
go: finding module for package github.com/golang-jwt/jwt/test
go: finding module for package github.com/golang-jwt/jwt
go: finding module for package github.com/golang-jwt/jwt/request
go: downloading github.com/golang-jwt/jwt v1.0.2
go: found github.com/golang-jwt/jwt in github.com/golang-jwt/jwt v3.2.1+incompatible
go: found github.com/golang-jwt/jwt/request in github.com/golang-jwt/jwt v3.2.1+incompatible
go: found github.com/golang-jwt/jwt/test in github.com/golang-jwt/jwt v3.2.1+incompatible
go: github.com/golang-jwt/jwt@v3.2.1+incompatible used for two different module paths (github.com/dgrijalva/jwt-go and github.com/golang-jwt/jwt)
```

I'm not sure why it tries to download  v1.0.2 (`go: downloading github.com/golang-jwt/jwt v1.0.2`).

I also try to replace import paths in my code with `gofmt -w -r '"github.com/dgrijalva/jwt-go" -> "github.com/golang-jwt/jwt-go"' .` then get this error:

```
$ gofmt -w -r '"github.com/dgrijalva/jwt-go" -> "github.com/golang-jwt/jwt-go"' .
$ go mod download github.com/golang-jwt/jwt
go mod download: module github.com/golang-jwt/jwt: not a known dependency
```

`go mod download github.com/golang-jwt/jwt@v3.2.1+incompatible` doesn't return any errors but it looks like it doesn't work:

```
$ gofmt -w -r '"github.com/dgrijalva/jwt-go" -> "github.com/golang-jwt/jwt-go"' .
$ go mod download github.com/golang-jwt/jwt@v3.2.1+incompatible
$ go test ./... -v
main.go:25:2: no required module provides package github.com/golang-jwt/jwt-go; to add it:
        go get github.com/golang-jwt/jwt-go
```

I'm wondering if https://github.com/golang-jwt/jwt/issues/30 could help. Btw, I'm using Go 1.16.6:

```
$ go version
go version go1.16.6 darwin/amd64
```

**Comment by jkawamoto** [comment]
I'm sorry I used the wrong repository name. This worked for me:

```
$ gofmt -w -r '"github.com/dgrijalva/jwt-go" -> "github.com/golang-jwt/jwt"' .
$ go get github.com/golang-jwt/jwt
```

**Comment by mfridman** [comment]
> I had a quick look into your PR and I fear that you are stuck in the middle for now. The `replace` route only works of you keep the original import path. Replacing the import path will not replace transitive imports.
> 
> My best guess would be to switch back to the old dgrijalva import path and use replace. Then once, your transitive dependency also switches to the new import path, remove the replace and switch the import path. Not really a good solution, but it is probably the "safest".
> 
> We probably should update the migration guide to reflect that you could run into this kind of problem with other transitive dependencies.

Ye, I don't know if there is a better solution here when using the `replace` directive. I believe this is related to https://github.com/golang/go/issues/26904 

I haven't been keeping a close eye on modules, but I think there is some work by @bcmills and the Go team to address such issues in 1.17 and/or 1.18

**Comment by mfridman** [comment]
@turkenh @jkawamoto We just landed module support, so I'd suggest dropping the `replace` if you're having troubles with transitive dependencies and instead importing this package as "github.com/golang-jwt/jwt/v4".

Closing this issue. Feel free to continue commenting and/or create a new issue.
