### ISSUE TITLE
key is of invalid type. What am i doing wrong?

### ISSUE THREAD

**Issue by ShyLionTjmn** [golang-jwt/jwt#38]
Got public key from my keycloak test server and passing it , base64 decoded, as return value in keyfinc.

https://play.golang.org/p/S_p2F6COoMq

**Comment by ShyLionTjmn** [comment]
I had to turn it to appropriate key type using x509.ParsePKIXPublicKey

**Comment by zhaiyjgithub** [comment]
I think maybe you use the incorrect sign method.
