### ISSUE TITLE
Parse - skip verification?

### ISSUE THREAD

**Issue by ShyLionTjmn** [golang-jwt/jwt#39]
How do i skip token verification? nil as keyfunc returns error

**Comment by owen-transcarent** [comment]
Hi @ShyLionTjmn 

Try something like this...

```
	adminStatus, _, err := new(jwt.Parser).ParseUnverified(token, jwt.MapClaims{})
	if err != nil {
		return err
	}
	if claims, ok := adminStatus.Claims.(jwt.MapClaims); ok {
		if claims["isAdmin"] == true {
			return nil
		}
	}
```

I hope this helps.

**Comment by oxisto** [comment]
You should *never* *ever* do this in production. Always verify the token. Closing this.

**Comment by owen-transcarent** [comment]
Hi @oxisto , agree you should never do this by itself. I think there is a valid use case though. 

1. Let's say you have a 3rd party JWT token and it is expensive to verify (requires a network call)If that 
2. When the code first gets the token do some sanity checks (is it empty, is it even a JWT, etc.)
3. There could also be something in the claims you'd like to verify before even proceeding
4. If that's all good, then proceed to call the 3rd party to verify  the JWT token (with the signature)
5. Use the result of the verify call appropriately

I admit this is a corner case and you should alway verify the token before actually using it.

**Comment by ShyLionTjmn** [comment]
I just need to extract claims from token, forwarded by auth proxy, which job to validate and check signature.
