### ISSUE TITLE
Still trying to understand 'ParseRSAPublicKeyFromPEM'

### ISSUE THREAD

**Issue by lknite** [golang-jwt/jwt#391]
Scenario:
- I'm working on an app and cli.
- The app runs in kubernetes and is configured with OIDC.
- My cli interacts with the app, and if the bearer token has expired, pops up a web browser to gather up credentials.

Everything works perfectly, except, in my app I have a hard coded value:
```
	SecretKey := "-----BEGIN CERTIFICATE-----\n" + "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBC..." + "\n-----END CERTIFICATE-----"

	key, err := jwt.ParseRSAPublicKeyFromPEM([]byte(SecretKey))
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	
	// Parse takes the token string and a function for looking up the key. The latter is especially
	// useful if you use multiple keys for your application.  The standard is to use 'kid' in the
	// head of the token to identify which key to use, but the parsed token (head and claims) is provided
	// to the callback, providing flexibility.
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		// Don't forget to validate the alg is what you expect:
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"])
		}

		// hmacSampleSecret is a []byte containing your secret, e.g. []byte("my_secret_key")
		return key, nil
	})
	if err != nil {
		return nil, err //log.Fatal(err)
	}
```

I'm using keycloak, and in the past I followed a [guide](https://vikaspogu.dev/posts/sso-jwt-golang/) .

The guide had me browse to a page on the keycloak server to get the RSA public key.  However, I don't understand why this is required.  What if the user was using a different provider other than keycloak, how would they obtain the RSA Public key?  I've configured OIDC on various apps such as harbor, and they always want the ProviderUrl, ClientID, and ClientSecret ... other than claims, but no keys.  Shouldn't the RSA Public key be something easily obtainable in an automatic way?

Perhaps the guide I followed didn't understand what the RSA Public key was for and mislead me.  On another page folks started talking about generating public and private keys.

I'd like my app to work with whatever OIDC provider the user might have.  So how can I get the needed value automatically?

Is it just the public https cert used by the keycloak server, or the public ca which was used to sign the keycloak server public cert?  (I generate tls certs for my apps automatically using cert-manager.)  That's usually what's required when people click 'verify' the issuer.  I could mount the ca.crt within the pod, then as long as the app used the system certs it should be able to verify.

**Comment by oxisto** [comment]
The RSA key (or any other public/private key such as ECDSA) is not the TLS certificate, but the certificate keycloak uses to sign the tokens. Keycloak uses the private part to sign. You need the public part to verify the token.

the easiest way to obtain this public key is using JSON Web Key Set. There is a plugin for JWT called https://github.com/MicahParks/keyfunc, this library can be used to obtain a JWKS from
an URL and can be supplied as the JWK keyfunc.

Most authorization servers such as keycloak present their public keys using JWKS. The URL depends on the keycloak url and the domain: https://www.keycloak.org/docs/latest/securing_apps/index.html#_certificate_endpoint

**Comment by oxisto** [comment]
Ah, and most OIDC providers implement https://datatracker.ietf.org/doc/html/rfc8414. This allows you to discover the JWKS URI from a standardized URL location. I am not sure if keyfunc supports finding the JWKS locations this way. @MicahParks ?

**Comment by MicahParks** [comment]
The [`keyfunc`](https://github.com/MicahParks/keyfunc) and [`jwkset`](https://github.com/MicahParks/jwkset) projects do not have any features for automatically finding JWK Sets. Specifying the location of a hosted JWK Set is an [optional feature of OpenID Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0-errata2.html).

In your case @lknite, it seems like the software you are writing in the context of this GitHub issue is for authenticating (and parsing) JWTs from Keycloak. This piece of software does not need to be aware of what OpenID Connect is or how it works, it only needs to authenticate JWTs.

The way you are currently doing it, with the embedded certificate is sufficient for some use cases, provided engineers know when and how to rotate the cert and redeploy in the event of key compromise, expiration, or other rotation. At the very least, the certificate is likely set to expire, after which point, the public key embedded in it shouldn't be used anymore.

Keycloak hosts a JWK Set for convenience. This JWK Set will automatically be updated with new public keys that will be used to sign JWTs. This allows programs to HTTP GET the JWK Set, cache the contents, then verify JWTs with the public key material found in there. In the case of Keycloak, the JWK Set is hosted at:
```
/realms/{realm-name}/protocol/openid-connect/certs
```
Here's the doc page for reference.
https://www.keycloak.org/docs/latest/securing_apps/index.html#_certificate_endpoint

If Keycloak were to change where the JWK Set is hosted, that would be a breaking change in my opinion. Such a change should require these docs to be updated and a new major release with a migration guide.

Given all of this, I would suggest you use the JWK Set Keycloak provides to get your public keys. Here's an example from the `keyfunc` project specifically for Keycloak. It will do all of the caching and updating for you automatically.
https://github.com/MicahParks/keyfunc/blob/master/examples/keycloak/main.go

**Comment by lknite** [comment]
Upon further review, I see the rfc mentioned above rfc8414, is the familiar /.well-known/openid-configuration, and what we are interested in regarding this issue is the 'jwks_uri' field, which is surprisingly OPTIONAL.  Being optional, makes me wonder if there is another way to verify the token.  In any case, I suspect requiring that field or flagging the OIDC server as incompatible if its missing may be appropriate.

I understand now that when I think of 'harbor' using OIDC, it is also the client in the exchange, so trusting the OIDC FQDN is all that's required, whereas in my use case I have a separate cli and app, and when the app gets the token, the only verification it has to ensure the token came from the trusted oidc server is the method we've been discussing here.  Ok, looking into consuming that 'jwks_uri' using the libraries you've mentioned.  I'll report my findings here for folks who happen to come across this issue later with the same questions.

**Comment by oxisto** [comment]
> * rfc8414

It’s unfortunately a little bit of a mess, in a way that RFC8414, which is an OAuth 2.0 related RFC says it’s optimal, but the use of the OpenID Connect (which builds upon OAuth 2.0) makes it required.

**Comment by lknite** [comment]
Some code for those who might be interested:

// get verification public certificates via oidc server
```
func initJwks() {
        /**
         * acquire jwks uri via rfc8414: begin
         */

        // initialize rest client
        client := &http.Client{
                Timeout: time.Second * 10,
        }
        uri := os.Getenv("OIDC_PROVIDER_URI") + "/.well-known/openid-configuration"
        log.Printf("uri: %v", uri)
        req, err := http.NewRequest("GET", uri, nil)
        if err != nil {
                log.Fatal(err)
        }

        // invoke method
        resp, err := client.Do(req)
        if err != nil {
                log.Fatal(err)
        }
        defer resp.Body.Close()

        //
        if resp.StatusCode != 200 {
                log.Fatal("jwks, StatusCode: " + strconv.Itoa(resp.StatusCode))
        }

        // read off body of response
        respBody, _ := io.ReadAll(resp.Body)

        //
        type Rfc8414 struct {
                Jwks_uri string `json:"jwks_uri"`
        }
        var oidc Rfc8414

        // parse json, acquire jwks_uri
        json.Unmarshal(respBody, &oidc)
        log.Printf("oidc.Jwks_uri: %v", oidc.Jwks_uri)

        /**
         * acquire jwks uri via rfc8414: end
         */

        //
        jwks, err = jwkset.NewDefaultHTTPClient([]string{oidc.Jwks_uri})
        if err != nil {
                log.Fatalf("Failed to create client JWK set. Error: %s", err)
        }
}
```

// verify tokens / get claims
```
                // Parse takes the token string and a function for looking up the key. The latter is especially
                // useful if you use multiple keys for your application.  The standard is to use 'kid' in the
                // head of the token to identify which key to use, however, the parsed token (head and claims)
                // is still provided to the callback, providing flexibility.
                token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
                        // Don't forget to validate the alg is what you expect:
                        //if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
                        //      return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"])
                        //}

                        // acquire 'kid' from header, this is used to identify which algo is being used by the oidc server
                        kid := token.Header["kid"].(string)

                        // use 'kid' to acquire key
                        jwk, err := jwks.KeyRead(r.Context(), kid)
                        if err != nil {
                                log.Fatalf("Failed to read key from client JWK set. Error: %s", err)
                        }
                        key := jwk.Key()

                        return key, nil
                })
                if err != nil {
                        fmt.Println(err)
                        return nil, err
                }

                if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
                        return claims, nil
                }

                return nil, errors.New("authentication failed")
```

**Comment by MicahParks** [comment]
@lknite did you take a look at the `keyfunc` Keycloak [example](https://github.com/MicahParks/keyfunc/blob/master/examples/keycloak/main.go)? It does what is in the example and a bit more.

**Comment by lknite** [comment]
Thanks again, I see now it lets you do the .Parse in a simpler way, thanks for the heads up.  I had seen that example but somehow ended up with the code above.  I'll see about simplifying things.
```go
token, err := jwt.Parse(jwtB64, jwks.Keyfunc)
```
