### ISSUE TITLE
Version v5 not found

### ISSUE THREAD

**Issue by RichGski** [golang-jwt/jwt#397]
I may be doing something wrong, but github.com/golang-jwt/jwt/v5 does not exist. I get a 404 error.

**Comment by mfridman** [comment]
It should be available. https://pkg.go.dev/github.com/golang-jwt/jwt/v5

```
go get github.com/golang-jwt/jwt/v5@latest
```

Can you provide a reproducible example?

**Comment by mfridman** [comment]
I'm afraid the image is not displaying. Going to close the issue, but feel free to re-open if there's a bit more details on the issue and/or set of commands you're running.
