### ISSUE TITLE
which golang-jwt/jwt version can be used  when building with golang1.13.8

### ISSUE THREAD

**Issue by cherishman2005** [golang-jwt/jwt#399]
* build golang1.13.8， and build errors:
```
/root/go/pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
/root/go/pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
```

* which golang-jwt/jwt version can be used  when building with golang1.13.8?

**Comment by oxisto** [comment]
https://github.com/golang-jwt/jwt/releases/tag/v3.2.1 is the latest one. The first v4.0 version already needs Go 1.15. Please be aware that Go 1.13 is quite old (> 4 years) and is definitely considered to be End-Of-Life and not supported by the Go team anymore.
