### ISSUE TITLE
Possible typo in ES512 signing method

### ISSUE THREAD

**Issue by logan-stern** [golang-jwt/jwt#422]
https://github.com/golang-jwt/jwt/blob/bc8bdca5cced1caa9787e4a1c313a3538544c877/ecdsa.go#L46

Should the CurveBits for ES512 be 512?

**Comment by oxisto** [comment]
This is confusing but correct :) ES512 uses a SHA-512 and P-521 curve. See https://datatracker.ietf.org/doc/html/rfc7518#section-3.1

**Comment by logan-stern** [comment]
> This is confusing but correctly implemented :) ES512 uses a SHA-512 and P-521 curve. See https://datatracker.ietf.org/doc/html/rfc7518#section-3.1

Aha, thank you for the clarification!
