### ISSUE TITLE
Community: Looking for a logo

### ISSUE THREAD

**Issue by oxisto** [golang-jwt/jwt#43]
Since this repo and organization are getting some traction it would be nice to have a little logo for the GitHub organization. Ideally something licensed as CC-0. Do we have any talented artists among our ranks?

**Comment by mfridman** [comment]
Couldn't we just use the auth0 JWT logo, MIT licensed, with proper attribution on the README

https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/LICENSE.txt

Or were you thinking about some fusion of a Gopher + JWT?

**Comment by oxisto** [comment]
> Or were you thinking about some fusion of a Gopher + JWT?

That would be very cool :)

**Comment by mfridman** [comment]
This is the best I could come up with, using the original logo with the https://excalidraw.com/ style.

Yay/nay?

![image](https://user-images.githubusercontent.com/6278244/152069983-928b8cfe-f8eb-445f-9789-6dad7fcc9cbf.png)

**Comment by lggomez** [comment]
+1 from me, looks simple enough but colorful and more distinctive than the autogenerated gh logo 🚀

**Comment by oxisto** [comment]
> This is the best I could come up with, using the original logo with the https://excalidraw.com/ style.
> 
> Yay/nay?
> 
> ![image](https://user-images.githubusercontent.com/6278244/152069983-928b8cfe-f8eb-445f-9789-6dad7fcc9cbf.png)

Can you give it a try how it looks as a smaller GH logo in the org?

**Comment by lggomez** [comment]
@oxisto I think it may need a little cutoff on the bottom as it seems to shrink a bit, altough almost unnoticeable:
<img width="297" alt="Captura de Pantalla 2022-02-06 a la(s) 14 00 37" src="https://user-images.githubusercontent.com/6326271/152692029-89f3f853-c882-4fb4-b15d-8762d6fa4abe.png">

**Comment by mfridman** [comment]
I updated it the logo a bit. Kept it simple.

Note sure if we need this, I assume yes, but #161 also updates the README to include the logo license.

<img src="https://user-images.githubusercontent.com/6278244/152896086-67295744-69ff-43f1-bf90-b46e6895ff72.png" width="400" height="400">

**Comment by mfridman** [comment]
Closing, good enough until something better comes along.
