### ISSUE TITLE
Add GitHub Discussions

### ISSUE THREAD

**Issue by mfridman** [golang-jwt/jwt#62]
What are your thoughts on adding [GitHub Discussions](https://docs.github.com/en/discussions)?

I noticed with the upstream repository [dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) a good chunk of the Issues were questions.

Alternatively (or in parallel), we can setup a GitHub Pages with a basic FAQ to address a lot of the recurring questions.

**Comment by ripienaar** [comment]
I like discussions, a pinned discussion that we edit to act as a FAQ is a good stop gap/focus point.

**Comment by mfridman** [comment]
Enabled.
