### ISSUE TITLE
Handling and migration of original project PRs

### ISSUE THREAD

**Issue by lggomez** [golang-jwt/jwt#7]
We have to define how to deal with the original project's PRs

We can either:
* Triage and port then manulally (we're talking about 42 as of today)
* Use some automated (albeit complicated) solution like https://github.com/NicholasBoll/github-migration

**Comment by lggomez** [comment]
Note that is is important to keep notified the original reporter, either by reference via addendum on the migrated issue or by CCing then via a new comment in the thread

This is a bit trickier, since whoever performs the migration will be the owner of the commit and not the original author, so the credit to the original author must be addressed by all means possible if the PR goes forward

**Comment by oxisto** [comment]
I have identified one or two interesting PRs and tried to start a conversation, whether the original authors want to migrate their code. For all sort of (copyright) reasons, I would not suggest just taking the code. Even if you provide a reference, it's really a grey area. So I would prefer, if the authors would move over their commits.

**Comment by lggomez** [comment]
> I have identified one or two interesting PRs and tried to start a conversation, whether the original authors want to migrate their code. For all sort of (copyright) reasons, I would not suggest just taking the code. Even if you provide a reference, it's really a grey area. So I would prefer, if the authors would move over their commits.

I haven't thought about that at a first glance but I agree it's a delicate nuance, so we'll leave it at suggestions pointing to this repo then. We can still do our implementations of the same ideas though (albeit more time consuming and less desired due to still having possible frictions with the original author of the PR)

**Comment by lggomez** [comment]
@mfridman @ripienaar @Waterdrips If you guys agree we can leave at this and close this issue to keep it as a guideline

**Comment by ripienaar** [comment]
Yes agree we can’t just take the PRs.
