### ISSUE TITLE
Add to awesome-go & misc

### ISSUE THREAD

**Issue by lggomez** [golang-jwt/jwt#88]
I opened https://github.com/avelino/awesome-go/pull/3695 to add this package to the list. @mfridman I requested you org access to coveralls, since it's one of the requirements (and it doesn't hurt to have a code coverage badge I guess)

If there are other lists or sites in which we should make a contribution adding the package (like #65) it'd be worth to mention them here

**Comment by mfridman** [comment]
Approved coveralls app.

I thought you had org access, were you not able to do this action? Or wanted a second set of eyes?

**Comment by lggomez** [comment]
It required permission from the org owner but since it required additional CI setup I ended up using this: https://gocover.io/github.com/golang-jwt/jwt

It may not generate a badge or anything but it is an online viewer of the go cover report, so that's fine by me. I updated the PR in awesome-go

**Comment by mfridman** [comment]
Ah ye, good ol' gocover.io

There is a badge here (which I assume is just an average):

http://gocover.io/_badge/github.com/golang-jwt/jwt

**Comment by mfridman** [comment]
Added in https://github.com/avelino/awesome-go/pull/4509 to awesome-go and we've since added coverage support.
