### ISSUE TITLE
v3.2.2+incompatible build have error

### ISSUE THREAD

**Issue by 4color** [golang-jwt/jwt#90]
github.com/golang-jwt/jwt
../pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
../pkg/mod/github.com/golang-jwt/jwt@v3.2.2+incompatible/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)

**Comment by oxisto** [comment]
Duplicate of https://github.com/golang-jwt/jwt/issues/50

Starting with `v3.2.2`, jwt-go required at least Go 1.15.

**Comment by mfridman** [comment]
Please consider updating your Go version if possible. Closing as no further action.
