### ISSUE TITLE
RSA err

### ISSUE THREAD

**Issue by zag07** [golang-jwt/jwt#99]
When I run the official example, an error occurs, but it does not appear when I use hmac

[recurrent link](https://play.golang.org/p/RN3D-W2Ra1t)

go version 1.17

**Comment by mfridman** [comment]
In the provided playground example there is no private key set, take a look at the example here:

https://github.com/dgrijalva/jwt-go/blob/master/http_example_test.go#L44

Can you provide us with a link to the example you're referring to?

**Comment by zag07** [comment]
https://pkg.go.dev/github.com/golang-jwt/jwt#example-package-UseTokenViaHTTP
oh, i see. thankyou  😊

**Comment by mfridman** [comment]
Closing. But feel free to continue commenting if you run into more issues on your original question.
